spring:
  profiles:
    # profile - dev, stage, prod
    active: dev

  application:
    name: inventory-service

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        #hibernate 방언 설정
        dialect: org.hibernate.dialect.PostgreSQLDialect
    #        default_batch_fetch_size: 50

    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
#      default 그룹
      group-id: order-group
#      offset이 존재하지 않을 경우 최초 저장된 위치부터 읽어옴.
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # ACKS 설정
      acks: 1
      # 1 - 리더 파티션에 한번 전송
      # 0 - acks 없음
      # -1 or all - 모든 복제본에 메시지가 저장
      retries: 5                   # 재시도 횟수
      enable-idempotence: true     # 멱등성 설정 (중복 전송 방지)
    
  # Redis 설정
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: "@sdc.com"

  # MySql 설정
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://127.0.0.1:5432/inventory-v0.1
    hikari:
      minimum-idle: 5
      maximum-pool-size: 50
    type: com.zaxxer.hikari.HikariDataSource
    username: sdc
    password: "@sdc.com"

server:
  port: 8080
  servlet:
    context-path: /inventory

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus