spring:
  profiles:
    # profile - dev, stage, prod
    active: dev

  application:
    name: inventory-service

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        #hibernate 방언 설정
        dialect: org.hibernate.dialect.PostgreSQLDialect
    #        default_batch_fetch_size: 50

    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # ACKS 설정
      acks: 1
      # 1 - 리더 파티션에 한번 전송
      # 0 - acks 없음
      # -1 or all - 모든 복제본에 메시지가 저장
      retries: 5                   # 재시도 횟수
      enable-idempotence: true     # 멱등성 설정 (중복 전송 방지)
    
  # Redis 설정
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  # MySql 설정
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://${POSTGRESQL_URL}:5433/inventory-v0.1
    hikari:
      minimum-idle: 5
      maximum-pool-size: 50
    type: com.zaxxer.hikari.HikariDataSource
    username: ${POSTGRESQL_NAME}
    password: ${POSTGRESQL_PW}

server:
  port: 8080
  servlet:
    context-path: /inventory

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus